---
title: "Olympic Rowing Predictions"
subtitle: "Stat135 - Predicting Paris 2024 Data Challenge"
author: "Joel, Lauren, Mia, Sam"
format: pdf
---

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(echo = TRUE, eval=F)

library(googlesheets4)
library(mosaic)
```

## Import the data
```{r}
#| label: import-data
knitr::opts_chunk$set(echo = TRUE, eval=F)

library(googlesheets4)
library(mosaic)
library(tidyverse)
olympic_dat0 <- readRDS(file=url("https://kcorreia.people.amherst.edu/Stat135/project_scull.Rds")) |>
  separate(Time, into=c("minute", "second"), sep=":", remove=F) |>
  mutate(across(c("minute", "second"), ~parse_number(.))
         , Time_Minutes = minute + (second/60)
         , RacingLane = parse_number(`Racing Line`)
         , RacingLane_f = factor(case_when(RacingLane %in% c(6) | is.na(RacingLane) ~ "Other"
                                    , RacingLane == 1 ~ "Lane 1"
                                    , RacingLane == 2 ~ "Lane 2"
                                    , RacingLane == 3 ~ "Lane 3 (Referent)"
                                    , RacingLane == 4 ~ "Lane 4"
                                    , RacingLane == 5 ~ "Lane 5")
                                 , levels=c("Lane 3 (Referent)", "Lane 1", "Lane 2", "Lane 4", "Lane 5", "Other")))


# check derivation
count(olympic_dat0, RacingLane, RacingLane_f)

# check numbers in each group of new variable
count(olympic_dat0, RacingLane_f)

```

## Descriptive Statistics

```{r}
#| label: desc-stats
 
# e.g, can use tally to compute descriptive statistics for categorical variables

tally(~RacingLane_f, data=olympic_dat0)
tally(~AnyPriorOlympics, data=olympic_dat0)
tally(~AnyPriorMedals, data=olympic_dat0)

# e.g., can use favstats to compute descriptive statistics for quantitative variables
favstats(~Time_Minutes, data=olympic_dat0)
favstats(~Height, data=olympic_dat0)
favstats(~Weight, data=olympic_dat0)
favstats(~Age, data=olympic_dat0)
gf_histogram( ~ Age, data=olympic_dat0, color="black"
             , xlab="Age")
gf_histogram( ~ Time_Minutes, data=olympic_dat0, color="black"
             , xlab="Time")
favstats(Time_Minutes ~ RacingLane_f, data = olympic_dat0)
# e.g., by group

groupedNation<-olympic_dat0 %>% 
  group_by(NOC) %>% 
  count() %>%
  ungroup() %>%
  mutate(freq. = 100 * n/79)

groupedOlympicCity<-olympic_dat0 %>% 
  group_by(OlympicCity) %>% 
  count() %>%
  ungroup() %>%
  mutate(freq. = 100 * n/79)

gf_bar( ~ OlympicCity, data=olympic_dat0
        , ylab="Number of Athletes", xlab = 'Olympic City', title='Number of Athletes per Olympic City') +
  theme(axis.text.x=element_text(angle=45,hjust=1))
```

## Plot(s)

```{r}
#| label: plotting

# title your plot(s), keeping in mind context and language matter
# be sure to label all axes appropriately 

# see the mosaic cheatsheet, and relevant labs and problem sets for how to
# code the plot you want (using one of the gf_XX functions)
# if you're still stuck or have a question about a particular aspect of the plot,
# come talk to me - I can help you!

gf_boxplot(Time_Minutes ~ RacingLane_f, data = olympic_dat0
           , xlab="Lane"
           , ylab="Time (minutes)"
           , title="Time verses Lane") 

#scatterplots so no concerning features so we can assume linearity for the regression model
gf_point(Time_Minutes ~ Height, data=olympic_dat0) %>% gf_lm(size=1.5,linetype="dashed")
gf_point(Time_Minutes ~ Weight, data=olympic_dat0) %>% gf_lm(size=1.5,linetype="dashed")
```


## Multiple Linear Regression Model 

```{r}
#| label: mlr

# include the code to fit your multiple linear regression model 
# including any checks for relevant assumptions
# and any inferential procedures you did 
# (e.g., hypothesis testing or confidence intervals)
# please use comments to indicate what you're doing

#create initial regression without categorical variable to see what distributions look like
mod <- lm(Time_Minutes ~ Height + Weight, data=olympic_dat0) 
msummary(mod)

#show distribution of the residuals to check for nearly normal
gf_histogram(~resid(mod2), color="black"
             , xlab="Residuals"
             , ylab="Time")

#check for equal variance
gf_point(resid(mod) ~ predict(mod), color="black"
         , xlab="Predicted Time (minutes)"
         , ylab="Time Residual (minutes)") |>
  gf_abline(intercept=0, slope=0, linetype="dashed", color="darkgrey")

#run model with racing lane
#we needed to remove some null values to be able to visualize the model 
mod2 <- lm(Time_Minutes ~ Height + Weight + RacingLane_f, data=na.omit(olympic_dat0))
msummary(mod2)

#Create Residual Plot
olympicResidualPlot <- olympic_dat0 |>
  mutate(resid(mod2)
         ,predict(mod2))

gf_point(Time_Minutes ~ Height, color = ~RacingLane_f, data = na.omit(olympic_dat0) , xlab = 'Height (cm)', ylab = 'Racing Time (minutes)', title ='Time verses Height') |>
gf_lm()

gf_point(Time_Minutes ~ Weight, color = ~RacingLane_f, data = na.omit(olympic_dat0) , xlab = 'Weight (kg)', ylab = 'Racing Time (minutes)', title ='Time verses Weight') |>
gf_lm()


confint(mod, level = 0.95)
confint(mod2, level = 0.95)
```

### Prediction

```{r}
#| label: predict

# include the code to make your prediction for an athlete who
# is expected to compete in the event this summer

# Prediction for Eliot Putnam

height <- 1.8796
weight <- 88.4505

# Prediction with no Racing Line Considered
9.332553 + (-0.002582 * height) + (-0.014838 * weight)

# Predictions with all Racing Lines considered
#lane 1
9.2711690 + (-0.0003517 * height) + (-0.0188197 * weight) + 0.1530032

#lane 2
9.2711690 + (-0.0003517 * height) + (-0.0188197 * weight) + -0.0451155

#lane 3
9.2711690 + (-0.0003517 * height) + (-0.0188197 * weight) 

#lane 4
9.2711690 + (-0.0003517 * height) + (-0.0188197 * weight) + -0.0087013

#lane 5
9.2711690 + (-0.0003517 * height) + (-0.0188197 * weight) + 0.0019666

#other lane
9.2711690 + (-0.0003517 * height) + (-0.0188197 * weight) + -0.2292808

print(prediction_no_RL)
print(predictions_RL)

  
```
